#!/bin/bash

# This script launches aletheia with an available terminal. For use with aletheia.desktop file.

ALETHEIA_PATH=${ALETHEIA_PATH:-""}
 
if ! command -v aletheia >/dev/null && [ "$ALETHEIA_PATH" == "" ]; then
	echo "Error: aletheia not installed (override with environment value ALETHEIA_PATH=)"
	exit 1
fi

if [ "$ALETHEIA_PATH" == "" ]; then
	ALETHEIA_PATH="$(which aletheia)"
else
	ALETHEIA_PATH="$(realpath "$ALETHEIA_PATH")"
fi

if [ ! -x "$ALETHEIA_PATH" ]; then
	if [ ! -e "$ALETHEIA_PATH" ]; then
		echo "Error: $ALETHEIA_PATH does not exist."
	else
		echo "Error: $ALETHEIA_PATH not executable"
	fi
	exit 1
fi

# To override automatic terminal selection, set TERMINAL= in ~/.aletheia/config
# to the basename of the terminal you wish to use, provided it's supported below

run_gnome() {
	/usr/libexec/gnome-terminal-server --app-id=org.gnome.aletheia --class=org.gnome.aletheia --name=org.gnome.aletheia >/dev/null 2>/dev/null &
	sleep 0.1
	gnome-terminal --app-id=org.gnome.aletheia --hide-menubar --geometry=48x14 -- "$ALETHEIA_PATH"
}

run_xfce4() {
	/usr/bin/xfce4-terminal --geometry=48x14 --title=Aletheia --icon=/usr/share/icons/aletheia.png --color-text=white --color-bg=black --command="$ALETHEIA_PATH"
}

run_konsole() {
	/usr/bin/konsole --hide-menubar --hide-tabbar -e "$ALETHEIA_PATH"
}

run_xterm() {
	xterm +sb -title Aletheia -geometry 48x14 -bg black -fg white -e "$ALETHEIA_PATH"
}

run_urxvt() {
	urxvt +sb -title Aletheia -geometry 48x14 -bg black -fg white -e "$ALETHEIA_PATH"
}

run_alacritty() {
	alacritty --class org.gnome.aletheia --title Aletheia -e "$ALETHEIA_PATH"
}

run_kitty() {
	kitty --class org.gnome.aletheia --title Aletheia -e "$ALETHEIA_PATH"
}

run_mate() {
	mate-terminal --class=org.gnome.aletheia --name=org.gnome.aletheia --hide-menubar --geometry 48x17 --title Aletheia -e "$ALETHEIA_PATH"
}

# If no TERMINAL= line set in ~/.aletheia/config, run what's available,
# starting with GNOME-Terminal.

run_available() {
	if [ -x /usr/libexec/gnome-terminal-server ] && command -v gnome-terminal >/dev/null; then
		run_gnome
	elif command -v /usr/bin/xfce4-terminal >/dev/null; then
		run_xfce4
	elif command -v konsole >/dev/null; then
		run_konsole
	elif command -v xterm >/dev/null; then
		run_xterm
	elif command -v urxvt >/dev/null; then
		run_urxvt
	elif command -v alacritty >/dev/null; then
		run_alacritty
	elif command -v kitty >/dev/null; then
		run_kitty
	elif command -v mate-terminal >/dev/null; then
		run_mate
	else
		if ( command -v zenity >/dev/null ); then
			zenity --info --text="No supported terminals available." --ok-label="OK" 2>/dev/null
		fi
		exit 1
	fi
}

# Check if ~/.aletheia/config has a TERMINAL= override option

if [ -e "$HOME/.aletheia/config" ]; then
	choice="$(grep "TERMINAL=" "$HOME/.aletheia/config")"
	choice="${choice#*=}"
	choice="${choice//\"/}"
	choice="${choice,,}"
fi

if [ -n "$choice" ]; then
	if [ "$choice" == "gnome-terminal" ]; then
		run_gnome
	elif [ "$choice" == "xfce4-terminal" ]; then
		run_xfce4
	elif [ "$choice" == "konsole" ]; then
		run_konsole
	elif [ "$choice" == "xterm" ]; then
		run_xterm
	elif [ "$choice" == "urxvt" ]; then
		run_urxvt
	elif [ "$choice" == "alacritty" ]; then
		run_alacritty
	elif [ "$choice" == "kitty" ]; then
		run_kitty
	elif [ "$choice" == "mate-terminal" ]; then
		run_mate
	else
		run_available
	fi
else
	run_available
fi

exit 0
