#!/bin/bash

CWD="$(pwd)"
SRCDIR="${SRCDIR:-..}"
VERSION="$(grep "VERSION=" < aletheia | cut -d'"' -f2)"

cd "$SRCDIR" || exit 1
if [ ! -d "aletheia-$VERSION" ]; then
	echo "Error: Source directory should be named aletheia-$VERSION"
	exit 1
fi

tar -czvf "$CWD/aletheia-$VERSION.tar.gz" --exclude=.git --exclude=.github --exclude="aletheia-$VERSION.tar.gz" --owner "$(whoami)" --group "$(groups | cut -d' ' -f1)" "aletheia-$VERSION/"

echo -e "\n$CWD/aletheia-$VERSION.tar.gz\n"
