#!/bin/bash

VERSION=${VERSION:-0.9.6}
REVISION=2
SRCDIR=${SRCDIR:-"."}
TMPDIR="/tmp/aletheia_${VERSION}-${REVISION}_all"

if [ -e "$TMPDIR" ]; then
	sudo rm -rf "$TMPDIR"
fi

mkdir -p "$TMPDIR"/DEBIAN "$TMPDIR"/usr/bin "$TMPDIR"/usr/share/man/man1/ "$TMPDIR"/usr/share/icons/

#cp "$SRCDIR/aletheia" "$TMPDIR"
#cp "$SRCDIR/aletheia.1" "$TMPDIR"

echo -e "Package: aletheia\nVersion: ${VERSION}\nArchitecture: all\nMaintainer: Brad Hermanson <apeitheo@gmail.com>\nDepends: pulseaudio-utils, calc, bc, gtts, espeak-ng, sox, ffmpeg, mplayer\nDescription: A CLI media player with pitch controls and voice feedback." >"$TMPDIR"/DEBIAN/control

cp "$SRCDIR/aletheia" "$TMPDIR/usr/bin/"
cp "$SRCDIR/aletheia.1" "$TMPDIR/usr/share/man/man1/"
cp "$SRCDIR/aletheia.png" "$TMPDIR/usr/share/icons/"

chmod 755 "$TMPDIR/usr/bin/aletheia"
chmod 644 "$TMPDIR/usr/share/man/man1/aletheia.1"
cd "$TMPDIR"
sudo chown -R root:root "$TMPDIR"
sudo dpkg-deb --build "$TMPDIR"
