#!/bin/bash

RED="\033[1;31m"
NOCOLOR="\033[0m"

if [ "$(whoami)" != "root" ]; then
	echo -e "${RED}Error:$NOCOLOR Needs root permission"
	exit 1
fi

VERSION="$(grep "VERSION=" < aletheia | cut -d'"' -f2)"
REVISION=6
SRCDIR=${SRCDIR:-"$(pwd)"}
TMPDIR="/tmp/aletheia_${VERSION}-${REVISION}_all"

if [ -e "$TMPDIR" ]; then
	rm -rf "$TMPDIR"
fi

mkdir -p "$TMPDIR"/DEBIAN "$TMPDIR"/usr/bin "$TMPDIR"/usr/share/man/man1/ "$TMPDIR"/usr/share/icons/ "$TMPDIR"/usr/share/applications/

echo -e "Package: aletheia\nVersion: ${VERSION}\nArchitecture: all\nMaintainer: Brad Hermanson <apeitheo@gmail.com>\nDepends: pulseaudio-utils, calc, bc, gtts, espeak-ng, sox, ffmpeg, mplayer, parallel, sqlite3\nDescription: A CLI media player with pitch controls and voice feedback." >"$TMPDIR"/DEBIAN/control

install -m 755 "$SRCDIR/aletheia" "$TMPDIR/usr/bin/"
install -m 755 "$SRCDIR/aletheia_desktop_launcher" "$TMPDIR/usr/bin/"
install -m 644 "$SRCDIR/aletheia.1" "$TMPDIR/usr/share/man/man1/"
install -m 644 "$SRCDIR/aletheia.desktop" "$TMPDIR/usr/share/applications/"
install -m 644 "$SRCDIR/aletheia.png" "$TMPDIR/usr/share/icons/"

cd "$TMPDIR" || exit 1
chown -R root:root "$TMPDIR"
dpkg-deb --build "$TMPDIR"
if [ -e "/tmp/aletheia_${VERSION}-${REVISION}_all.deb" ]; then
	mv "/tmp/aletheia_${VERSION}-${REVISION}_all.deb" "$SRCDIR"
	echo "Moved aletheia_${VERSION}-${REVISION}_all.deb to $SRCDIR"
else
	echo -e "${RED}Error:$NOCOLOR Package creation not successful."
	exit 1
fi

exit 0
