#!/bin/bash

GREEN="\033[1;32m"
BLUE="\033[1;36m"
NOCOLOR="\033[0m"
RED="\033[1;31m"
YELLOW="\033[1;33m"

DESTDIR=${DESTDIR:-/usr/local}

QUIT=false
USER="$(whoami)"

echo -ne "${GREEN}Aletheia $(grep "VERSION=" < aletheia | cut -d'"' -f2)\n\n"
echo -ne "${BLUE}Checking for dependencies...\n\n"

check_dep() {
	local dependency_name="$1"

	echo -ne "${NOCOLOR}Checking for $dependency_name... "

	if [ "$(which "$dependency_name" 2>/dev/null)" == "" ]; then
		echo -e "${RED}no"
		QUIT=true
	else
		echo -e "${GREEN}yes"
	fi
}

check_dep pactl
check_dep calc
check_dep bc
check_dep gtts-cli
check_dep play
check_dep espeak-ng
check_dep sox
check_dep ffprobe
check_dep ffmpeg
check_dep iconv
check_dep mplayer
check_dep parallel
check_dep sqlite3
check_dep isnum

if [ "$QUIT" == true ]; then
	echo -ne "\n${RED}Error: Unresolved dependencies$NOCOLOR\n"
	exit 1
fi

if [ ! -w "$DESTDIR" ]; then
	echo -e "\n${RED}Error:$NOCOLOR Need root permission to install in $DESTDIR"
	exit 1
fi

echo -ne "\n${NOCOLOR}Installing... $NOCOLOR"

DESTDIR=${DESTDIR%/}

mkdir -p "$DESTDIR/bin/"
mkdir -p "$DESTDIR/share/man/man1/"
mkdir -p "$DESTDIR/share/applications"
mkdir -p "$DESTDIR/share/icons"

FAIL=false

if ! install -m 755 aletheia "$DESTDIR/bin/"; then
	FAIL=true
fi
if ! install -m 755 aletheia_desktop_launcher "$DESTDIR/bin/"; then
	FAIL=true
fi
if ! install -m 644 aletheia.1 "$DESTDIR/share/man/man1/"; then
	FAIL=true
fi
if ! install -m 644 aletheia.desktop "$DESTDIR/share/applications/"; then
	FAIL=true
fi
if ! install -m 644 aletheia.png "$DESTDIR/share/icons/"; then
	FAIL=true
fi

FILES[0]="${DESTDIR}/bin/aletheia"
FILES[1]="${DESTDIR}/bin/aletheia_desktop_launcher"
FILES[2]="${DESTDIR}/share/man/man1/aletheia.1"
FILES[3]="${DESTDIR}/share/applications/aletheia.desktop"
FILES[4]="${DESTDIR}/share/icons/aletheia.png"

for i in $(seq 0 $((${#FILES[@]}-1))); do
	chown "$USER:$USER" "${FILES[i]}"
done

if ! $FAIL; then
	echo -ne "${GREEN}done$NOCOLOR"
	if ! mandb >/dev/null 2>/dev/null; then
		echo "${YELLOW}Warning:$NOCOLOR mandb failed"
	fi

	echo -e "\n"

	for i in $(seq 0 $((${#FILES[@]}-1))); do
		echo "${FILES[i]}"
	done

	if [ "$DESTDIR" != "/usr/local" ] && [ "$DESTDIR" != "/usr/local/" ]; then
		echo -e "\n${NOCOLOR}Use ${GREEN}DESTDIR=${DESTDIR} ./uninstall$NOCOLOR to remove"
	else
		echo -e "\n${NOCOLOR}Use ${GREEN}./uninstall$NOCOLOR to remove"
	fi
	exit 0
else
	echo -e "\n${RED}Install not successful.$NOCOLOR\n"
	exit 1
fi
